site_name: Contrast-agent based perfusion MRI lexicon (CAPLEX)
site_description: CAPLEX
site_author: Open Science Initiative for Perfusion Imaging (OSIPI)
repo_url: https://github.com/OSIPI/OSIPI_CAPLEX
repo_name: OSIPI_CAPLEX
# Legal requirement under GDPR to allow changing cookie settings at all times!!!
copyright: >
  <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  logo: osipiImgs/OSIPI_logo.png
  favicon: osipiImgs/OSIPI_logo_only_square.png
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - search.suggest
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
    annotation: material/plus-circle
    repo: fontawesome/brands/github

docs_dir: docs

nav:
  - Overview:
      - About Caplex: index.md
      - CAPLEX structure: structure.md
      - How to use the website: qualityOfLife.md
      - How to contribute: improved-contribution-tutorial.md
  - Sections:
    - Q - Quantities: quantities.md
    - M - Perfusion models: perfusionModels.md
    - P - Perfusion processes: perfusionProcesses.md
    - G - General purpose processes: generalPurposeProcesses.md
    - D - Derived processes: derivedProcesses.md
  - Implementation Resources:
    - DCE/DSC resources:
      - DCE literature library: dceliterature.md
    - Software tools:
      - Software overview: softwareOverview.md
      - Data simulation tools: simulationTools.md
      - Analysis toolboxes: analysisToolboxes.md
    - Sample datasets: sampleDatasets.md

plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - attr_list
  - md_in_html
  - abbr

extra:
  og:
    type: website
    title: Contrast-agent based perfusion MRI lexicon (CAPLEX)
    description: CAPLEX
    image: Social Card.png
    url: https://osipi.github.io/OSIPI_CAPLEX/

extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-27M7GKVZFQ
    feedback:
        title: Was this page helpful?
        ratings:
          - icon: material/emoticon-happy-outline
            name: This page was helpful
            data: 1
            note: >-
              Thanks for your feedback! Help us improve this page by
              using our <a href="https://forms.gle/dsfUEZx6P91rBwJe6" target="_blank" rel="noopener">feedback form</a>.
          - icon: material/emoticon-sad-outline
            name: This page could be improved
            data: 0
            note: >-
              Thanks for your feedback! Help us improve this page by
              using our <a href="https://forms.gle/dsfUEZx6P91rBwJe6" target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our lexicon and whether users
      find what they're searching for. With your consent, you're helping us to
      make our lexicon better.
